name: apps
description: Aplikasi m-bangun

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flushbar: ^1.5.0
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.0.1
  image_picker: ^0.6.1+8
  flutter_secure_storage: ^3.3.1+1
  intl: ^0.16.1
  connectivity:
  splashscreen:
  datetime_picker_formfield: ^1.0.0
  custom_splash: ^0.0.2
  route_transitions: ^1.0.2
  random_string: ^2.0.1
  intro_slider: ^2.2.8
  toast: ^0.1.5
  local_auth: ^0.6.1+3
  provider: ^4.0.2
  pk_skeleton: ^0.0.2
  shared_preferences: ^0.5.3+4
  google_sign_in: ^4.5.1
  loading_animations: ^2.1.0
  empty_widget: ^0.0.1
  rounded_loading_button: ^1.0.0
  expansion_tile_card: ^1.0.3
  carousel_pro: ^1.0.0
#  firebase_admob: ^0.9.3+1
  bezier_chart: ^1.0.16
  jiffy: ^3.0.1
  floating_search_bar: ^0.3.0
  fl_chart: ^0.8.7
  package_info: ^0.4.0+9
  url_launcher: ^5.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo-icon.png
    - assets/kartu_nama.png
    - assets/logo-text.png
    - assets/images/shield.png
    - assets/images/lock.png
    - assets/images/notifications-on.png
    - assets/images/arrow-point-to-right.png
    - assets/images/speech-bubbles.png
    - assets/images/user.png
    - assets/images/cellular-connection-2-clipped-2.png
    - assets/images/group-623.png
    - assets/images/search-3.png
    - assets/images/capacity-clipped-2.png
    - assets/images/cap-clipped-2.png
    - assets/images/border-clipped.png
    - assets/images/wifi-2-clipped-2.png
    - assets/background1.png
    - assets/full-bloom.png
    - assets/mountains.jpg
    - assets/cinta-rakyat.jpg
    - assets/splace.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: LinoWrite
      fonts:
        - asset: assets/fonts/linowrite/linowrite.ttf

    - family: SUNDAY
      fonts:
        - asset: assets/fonts/SUNDAY/SUNDAY.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf

    - family: OpenSans-Semibold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Semibold.ttf

    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-ExtraBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
