name: apps
description: Aplikasi m-bangun

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.6+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  flushbar: ^1.5.0
  modal_progress_hud: ^0.1.3
  http_auth: ^0.3.0
  bubble_tab_indicator: ^0.1.4
  font_awesome_flutter: ^8.0.1
  image_picker: ^0.6.7+1
  flutter_secure_storage: ^3.3.1+1
  money2: ^1.4.0
  intl: ^0.16.1
  connectivity:
  splashscreen:
  datetime_picker_formfield: ^1.0.0
  custom_splash: ^0.0.2
  route_transitions: ^1.0.2
  random_string: ^2.0.1
  intro_slider: ^2.2.8
  toast: ^0.1.5
  local_auth: ^0.6.1+3
  provider: ^3.1.0
  percent_indicator: ^2.1.3
  pk_skeleton: ^0.0.2
  shared_preferences: ^0.5.3+4
  google_sign_in: ^4.5.1
  loading_animations: ^2.1.0
  empty_widget: ^0.0.1
  rounded_loading_button: ^1.0.0
  expansion_tile_card: ^1.0.3
  carousel_pro: ^1.0.0
  flutter_cache_manager: ^1.4.1
  flutter_html: ^1.0.0
  flutter_multi_formatter: ^1.1.6
  bezier_chart: ^1.0.16
  jiffy: ^3.0.1
  floating_search_bar: ^0.3.0
  fl_chart: ^0.8.7
  package_info: ^0.4.0+9
  url_launcher: ^5.1.4
  mime: ^0.9.6+3
  pinch_zoom_image_last: ^0.3.1
  flutter_signature_pad: ^2.0.2
  advance_pdf_viewer: ^1.1.6
  webview_flutter: ^0.3.22+1
  random_color: ^1.0.5
  flutter_wordpress: ^0.2.1
  carousel_slider: ^2.2.1
  multi_image_picker: ^4.6.9
  woocommerce: ^0.9.6
  gender_selection: ^0.0.8
  sliverbar_with_card: ^0.1.5
  smooth_star_rating: 1.1.1
  palette_generator: ^0.2.3
  grouped_list: ^3.3.0
  flutter_countdown_timer: ^1.0.0
  flutter_spinkit: ^4.1.2
  fw_ticket: ^0.1.1
  dotted_line: ^2.0.1
  multipart_request: ^0.3.1
  html_editor: ^1.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/icons/verified.png
    - assets/icons/worker.png
    - assets/icons/freeshipping.png
    - assets/test.pdf
    - assets/img/a.png
    - assets/img/waiting.png
    - assets/img/packing.png
    - assets/img/dikirim.png
    - assets/img/sad.png
    - assets/shipping_background.png
    - assets/icons/store.png
    - assets/images/splace-background.png
    - assets/bottom_yellow.png
    - assets/kategori/bahan_bangunan.png
    - assets/kategori/furniture.png
    - assets/kategori/bata_putih.png
    - assets/kategori/roof.png
    - assets/kategori/beton.png
    - assets/kategori/kayu.png
    - assets/kategori/pasir.png
    - assets/kategori/paint.png
    - assets/kategori/semen.png
    - assets/kategori/plumbing.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: WorkSansRegular
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Regular.ttf

    - family: LinoWrite
      fonts:
        - asset: assets/fonts/linowrite/linowrite.ttf

    - family: SUNDAY
      fonts:
        - asset: assets/fonts/SUNDAY/SUNDAY.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Bold.ttf

    - family: OpenSans-Semibold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Semibold.ttf

    - family: OpenSans-ExtraBold
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-ExtraBold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/open-sans/OpenSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
